# Generated by Django 3.1.2 on 2020-10-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='student',
        ),
    ]
